name: Run tests

on:
    push:
    pull_request:

jobs:
    test:
        strategy:
            matrix:
                node: [22.x, 24.x]
                os: [ubuntu-latest, windows-latest]
                include:
                    # The minimum version allowed by "engines" in package.json
                    - node: 22.19.0
                      os: ubuntu-latest
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm test

    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: Use Node.js 24.x
              uses: actions/setup-node@v7
              with:
                  node-version: 24.x
            - run: npm install
            - run: npm run coverage
            - run: npm run coverage:check
